### ISSUE TITLE
请问有处理后的webnlg数据集吗？

### ISSUE THREAD

**Issue by niuweicai** [Anery/RSAN#2]
终于等到了您的这篇论文的开源代码，非常感谢，我想问一下您方便提供一份处理过后的webnlg数据吗？

**Comment by angelotran05** [comment]
I am grateful if you can provide the WebNLG dataset. Thank you for your consideration.

**Comment by niuweicai** [comment]
有的





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Angelo"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 晚上10:25
收件人: "Anery/RSAN"<RSAN@noreply.github.com&gt;; 
抄送: "牛伟才"<605851710@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Anery/RSAN] 请问有处理后的webnlg数据集吗？ (#2)





 
I am grateful if you can provide the WebNLG dataset. Thank you for your consideration.

**Comment by zlh-source** [comment]
> 有的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Angelo"<notifications@github.com&gt;; 发送时间: 2020年10月15日(星期四) 晚上10:25 收件人: "Anery/RSAN"<RSAN@noreply.github.com&gt;; 抄送: "牛伟才"<605851710@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Anery/RSAN] 请问有处理后的webnlg数据集吗？ (#2) I am grateful if you can provide the WebNLG dataset. Thank you for your consideration. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

在哪能找到“处理过后的webnlg数据”？

**Comment by Anery** [comment]
抱歉回复晚了，已上传webnlg，与原始NYT格式一致

Sorry for the late reply. WebNLG has been uploaded, which is consistent with the original NYT format

**Comment by angelotran05** [comment]
Thank you for sharing the data.
-------------------------------
Van-Hien, Tran
Computational Linguistics Lab.
Graduate of Information Science, Nara Institute of Science and Technology.
Email: hien.tran.uet@gmail.com / tran.van_hien.ts1*@i
<hientv@vnu.edu.vn>s.naist.jp <http://s.naist.jp>*

**Comment by angelotran05** [comment]
Thank you for sharing the data.
