### ISSUE TITLE
关于table 2 的问题

### ISSUE THREAD

**Issue by zlh-source** [Anery/RSAN#3]
您好， 
您的论文里面Table 2中说WDec在WebNLG上的F1为0.735，但是WDec的论文里并没有公布WebNLG的相关数据，请问这是您自己测试出来的么？

**Comment by Anery** [comment]
是的，我用WDec作者提供的源代码测试的结果。我用的WebNLG数据已经上传，您可以用他们的代码试一试

Yes, I tested with their source code. The WebNLG data I used has been uploaded, you can have a try.

**Comment by zlh-source** [comment]
您好，ETL-Span这个模型的论文里报的NYT和WebNLG的分数分别是78.0%和83.1%。但是您的table-2里写的是79.1%和69.3%。这是为什么？
