### ISSUE TITLE
关于Table 2的数据问题

### ISSUE THREAD

**Issue by zlh-source** [Anery/RSAN#6]
您好，ETL-Span这个模型的论文里报的NYT和WebNLG的分数分别是78.0%和83.1%。但是您的table-2里写的是79.1%和69.3%。这是为什么？

**Comment by Anery** [comment]
你好，我这篇论文提交时引用的是ETL-Span的arxiv版本，当时他们的结果就是我文章里的79.1%和69.3%；等到camera ready的时候他们修改了结果，我为了和审稿时保持一致就没有改。
ETL-Span有开源代码，具体以他们的代码为准吧:)
