### ISSUE TITLE
最终结果

### ISSUE THREAD

**Issue by zhangzhiyi0108** [Anery/RSAN#8]
您好，我在我的机器上跑出的结果达不到论文里的效果（12G的GPU），请问是什么原因呢

**Comment by Anery** [comment]
现在是什么效果？跑了几个epoch？参数和论文里一致吗

**Comment by zhangzhiyi0108** [comment]
现在是和论文中结果相差1%左右，参数和论文中一致






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anery/RSAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anery/RSAN] 最终结果 (#8)





 
现在是什么效果？跑了几个epoch？参数和论文里一致吗

**Comment by Anery** [comment]
这个误差我觉得蛮正常的..可以试试多跑几次，再多跑几个epoch
我那个结果也是跑了几次取平均 每次也都有差异

**Comment by zhangzhiyi0108** [comment]
好的，谢谢您，我看您是在NYT数据集上跑100个epoch，webNLG上跑200个epoch，是这样子吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anery/RSAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anery/RSAN] 最终结果 (#8)





 
这个误差我觉得蛮正常的..可以试试多跑几次，再多跑几个epoch
 我那个结果也是跑了几次取平均 每次也都有差异

**Comment by Anery** [comment]
是，或者epoch可以设置成-1，让它一直跑，取到效果最好的模型

**Comment by zhangzhiyi0108** [comment]
好的，非常感谢您的回复和建议


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anery/RSAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anery/RSAN] 最终结果 (#8)





 
是，或者epoch可以设置成-1，让它一直跑，取到效果最好的模型

**Comment by ShaoZhangHao** [comment]
你好 请问你在NYT数据集上跑了多少个周期能大概复现出论文中的结果 我跑了100个周期 但是仅仅达到50%的精度
